#!/usr/bin/env python3
import sys, pathlib, yaml, textwrap

def die(msg): sys.exit(f"[generate_ns3] {msg}")
if len(sys.argv) != 2: die("usage: generate_ns3.py <config.unified.yaml>")

cfg = yaml.safe_load(pathlib.Path(sys.argv[1]).read_text())

# Load from the unified YAML structure
sim_cfg = cfg.get("simulation", {})
sim_name = sim_cfg.get("name", "NS3_Network")
sim_time = sim_cfg.get("duration", 10)
nodes    = cfg["nodes"]
links    = cfg["connections"]
# Use the traffic_flows key, falling back to traffic for compatibility
traffic  = cfg.get("traffic_flows") or cfg.get("traffic")

def cpp_id(s): return "".join(c if c.isalnum() else "_" for c in s)
node_cpp = {n["name"]: cpp_id(n["name"]) for n in nodes}
node_map = {n["name"]: n for n in nodes}

out_cc = f"{cpp_id(sim_name)}.cc"

# C++ Templates
C_HEAD = textwrap.dedent(f"""\
    /* AUTOGENERATED from {pathlib.Path(sys.argv[1]).name} */
    #include "ns3/core-module.h"
    #include "ns3/network-module.h"
    #include "ns3/internet-module.h"
    #include "ns3/point-to-point-module.h"
    #include "ns3/csma-module.h"
    #include "ns3/wifi-module.h"
    #include "ns3/mobility-module.h"
    #include "ns3/applications-module.h"

    using namespace ns3;
    NS_LOG_COMPONENT_DEFINE("{sim_name}");

    int main(int argc, char* argv[]) {{
      Time::SetResolution(Time::NS);
      CommandLine cmd; cmd.Parse(argc, argv);
      NS_LOG_UNCOND("===== {sim_name} start =====");
""")
C_TAIL = textwrap.dedent(f"""\
      NS_LOG_INFO("===== Running simulation =====");
      Simulator::Run();
      Simulator::Destroy();
      NS_LOG_UNCOND("===== Simulation end =====");
      return 0;
    }}
""")

code = [C_HEAD]

# Node Creation & Stack Installation
code.append("  NodeContainer allNodes;")
for n in nodes:
    code.append(f"  Ptr<Node> {node_cpp[n['name']]} = CreateObject<Node>();")
    code.append(f"  allNodes.Add({node_cpp[n['name']]});")
code.append("\n  InternetStackHelper internet;")
code.append("  internet.Install(allNodes);")
code.append('\n  MobilityHelper mobility;')
code.append('  mobility.SetMobilityModel("ns3::ConstantPositionMobilityModel");')
code.append("  mobility.Install(allNodes);")
code.append("")

# Link Creation
addr_oct = 1
for idx, ln in enumerate(links, 1):
    ltype = ln["type"]
    src_n, dst_n = ln['endpoints'][0]['node'], ln['endpoints'][1]['node']
    src_cpp, dst_cpp = node_cpp[src_n], node_cpp[dst_n]
    
    devs = f"linkDevices{idx}"
    tag = f"link{idx}"

    code.append(f'  NS_LOG_INFO("Creating {ltype} link between {src_n} and {dst_n}");')
    code.append(f"  NodeContainer linkNodes({src_cpp}, {dst_cpp});")
    code.append(f"  NetDeviceContainer {devs};")

    if ltype == "wifi":
        # In Wi-Fi, the endpoint order matters: STA -> AP
        sta_cpp, ap_cpp = src_cpp, dst_cpp
        code.extend(textwrap.dedent(f"""\
          {{
            YansWifiChannelHelper channel = YansWifiChannelHelper::Default();
            YansWifiPhyHelper phy;
            phy.SetChannel(channel.Create());

            WifiHelper wifi;
            wifi.SetStandard(WIFI_STANDARD_80211g);
            wifi.SetRemoteStationManager("ns3::AarfWifiManager");

            WifiMacHelper mac;
            Ssid ssid = Ssid("{tag}");
            
            mac.SetType("ns3::StaWifiMac", "Ssid", SsidValue(ssid), "ActiveProbing", BooleanValue(false));
            NetDeviceContainer staDevices = wifi.Install(phy, mac, {sta_cpp});

            mac.SetType("ns3::ApWifiMac", "Ssid", SsidValue(ssid));
            NetDeviceContainer apDevices = wifi.Install(phy, mac, {ap_cpp});

            {devs}.Add(staDevices);
            {devs}.Add(apDevices);
          }}
        """).splitlines())
    else: # p2p or csma
        params = ln.get("parameters", {})
        rate = params.get("datarate", "100Mbps")
        dly  = params.get("delay", "2ms")
        
        helper_var  = f"linkHelper{idx}"
        helper_class = "PointToPointHelper" if ltype == "p2p" else "CsmaHelper"
        
        code.append(f"  {helper_class} {helper_var};")
        code.append(f'  {helper_var}.SetChannelAttribute("Delay", StringValue("{dly}"));')
        if ltype == "p2p":
            code.append(f'  {helper_var}.SetDeviceAttribute("DataRate", StringValue("{rate}"));')
        code.append(f"  {devs} = {helper_var}.Install(linkNodes);")

    code.append(f'  Ipv4AddressHelper ipv4; // Link {idx}')
    code.append(f'  ipv4.SetBase("10.{addr_oct}.0.0", "255.255.255.0");')
    code.append(f'  ipv4.Assign({devs});\n')
    addr_oct += 1

# Auto-Routing
code.append('  Ipv4GlobalRoutingHelper::PopulateRoutingTables();\n')

# Traffic Generation
if not traffic:
    sinks  = [n for n in nodes if n["role"] == "sink"]
    if not sinks: die("No sink node and no 'traffic_flows' section in YAML.")
    default_sink = sinks[0]["name"]
    traffic = [{"source": n["name"], "sink": default_sink}
               for n in nodes if n["role"] == "source"]

code.append('  NS_LOG_INFO("Installing applications...");')
code.append("  uint16_t sinkPort = 8080;")

for i, t in enumerate(traffic, 1):
    src_node_name = t['source']
    sink_node_name = t['sink']
    params = t.get("parameters", {})
    rate   = params.get("rate", "1Mbps")
    psize  = params.get("packet_size", 1024)
    start  = params.get("start_time", 1.0)
    stop   = params.get("stop_time", sim_time)
    
    src_cpp = node_cpp[src_node_name]
    sink_cpp = node_cpp[sink_node_name]

    code.extend(textwrap.dedent(f"""\
      // Flow {i}: {src_node_name} -> {sink_node_name}
      {{
        Ipv4Address sinkAddress = {sink_cpp}->GetObject<Ipv4>()->GetAddress(1, 0).GetLocal();
        PacketSinkHelper packetSinkHelper("ns3::UdpSocketFactory", InetSocketAddress(Ipv4Address::GetAny(), sinkPort));
        ApplicationContainer sinkApps = packetSinkHelper.Install({sink_cpp});
        sinkApps.Start(Seconds(0.0));
        sinkApps.Stop(Seconds({sim_time}));

        OnOffHelper onOffHelper("ns3::UdpSocketFactory", InetSocketAddress(sinkAddress, sinkPort));
        onOffHelper.SetAttribute("DataRate", StringValue("{rate}"));
        onOffHelper.SetAttribute("PacketSize", UintegerValue({psize}));

        ApplicationContainer sourceApps = onOffHelper.Install({src_cpp});
        sourceApps.Start(Seconds({start}));
        sourceApps.Stop(Seconds({stop}));
      }}
    """).splitlines())


code.append(C_TAIL)

pathlib.Path(out_cc).write_text("\n".join(code))
print(f"[generate_ns3] Wrote C++ simulation file to {out_cc}")