#!/usr/bin/env python3
import sys, pathlib, yaml, textwrap

def die(msg): sys.exit(f"[generate_ns3] {msg}")
if len(sys.argv) != 2: die("usage: generate_ns3.py <config.unified.yaml>")

cfg = yaml.safe_load(pathlib.Path(sys.argv[1]).read_text())

sim_cfg = cfg.get("simulation", {})
sim_name = sim_cfg.get("name", "NS3_Network")
sim_time = sim_cfg.get("duration", 10)
nodes    = cfg["nodes"]
links    = cfg["connections"]
traffic  = cfg.get("traffic_flows") or cfg.get("traffic")

def cpp_id(s): return "".join(c if c.isalnum() else "_" for c in s)
node_cpp = {n["name"]: cpp_id(n["name"]) for n in nodes}
node_map = {n["name"]: n for n in nodes}

out_cc = f"{cpp_id(sim_name)}.cc"

C_HEAD = textwrap.dedent(f"""\
    /* AUTOGENERATED from {pathlib.Path(sys.argv[1]).name} */
    #include "ns3/core-module.h"
    #include "ns3/network-module.h"
    #include "ns3/internet-module.h"
    #include "ns3/point-to-point-module.h"
    #include "ns3/csma-module.h"
    #include "ns3/wifi-module.h"
    #include "ns3/mobility-module.h"
    #include "ns3/applications-module.h"
    #include "ns3/netanim-module.h"

    using namespace ns3;
    NS_LOG_COMPONENT_DEFINE("{sim_name}");

    static void RxPacket(Ptr<const Packet> packet, const Address &address)
    {{
        NS_LOG_UNCOND("Time: " << Simulator::Now().GetSeconds() << "s | Sink Received " << packet->GetSize() << " bytes");
    }}

    int main(int argc, char* argv[]) {{
      Time::SetResolution(Time::NS);
      CommandLine cmd; cmd.Parse(argc, argv);
      NS_LOG_UNCOND("===== {sim_name} setup start =====");
""")
C_TAIL = textwrap.dedent(f"""\
      NS_LOG_UNCOND("===== Running simulation =====");
      Simulator::Run();
      Simulator::Destroy();
      NS_LOG_UNCOND("===== Simulation end =====");
      return 0;
    }}
""")

code = [C_HEAD]

code.append("  NodeContainer allNodes;")
for n in nodes:
    code.append(f"  Ptr<Node> {node_cpp[n['name']]} = CreateObject<Node>();")
    code.append(f"  allNodes.Add({node_cpp[n['name']]});")
code.append("\n  InternetStackHelper internet;")
code.append("  internet.Install(allNodes);")
code.append('\n  MobilityHelper mobility;')
code.append('  mobility.SetMobilityModel("ns3::ConstantPositionMobilityModel");')
code.append("  mobility.Install(allNodes);")
code.append("")

addr_oct = 1
for idx, ln in enumerate(links, 1):
    ltype = ln["type"]
    src_n, dst_n = ln['endpoints'][0]['node'], ln['endpoints'][1]['node']
    src_cpp, dst_cpp = node_cpp[src_n], node_cpp[dst_n]
    
    code.append("  {")

    indented_code = []
    indented_code.append(f"NodeContainer linkNodes({src_cpp}, {dst_cpp});")
    indented_code.append(f"NetDeviceContainer linkDevices;")

    if ltype == "wifi":
        sta_cpp, ap_cpp = src_cpp, dst_cpp
        indented_code.extend(textwrap.dedent(f"""\
          YansWifiChannelHelper channel = YansWifiChannelHelper::Default();
          YansWifiPhyHelper phy;
          phy.SetChannel(channel.Create());
          phy.EnablePcapAll("link{idx}");
          WifiHelper wifi;
          wifi.SetStandard(WIFI_STANDARD_80211g);
          wifi.SetRemoteStationManager("ns3::AarfWifiManager");
          WifiMacHelper mac;
          Ssid ssid = Ssid("link{idx}");
          mac.SetType("ns3::StaWifiMac", "Ssid", SsidValue(ssid), "ActiveProbing", BooleanValue(false));
          NetDeviceContainer staDevices = wifi.Install(phy, mac, {sta_cpp});
          mac.SetType("ns3::ApWifiMac", "Ssid", SsidValue(ssid));
          NetDeviceContainer apDevices = wifi.Install(phy, mac, {ap_cpp});
          linkDevices.Add(staDevices);
          linkDevices.Add(apDevices);
        """).splitlines())
    else:
        params = ln.get("parameters", {})
        rate = params.get("datarate", "100Mbps")
        dly  = params.get("delay", "2ms")
        helper_class = "PointToPointHelper" if ltype == "p2p" else "CsmaHelper"
        indented_code.append(f"{helper_class} helper;")
        indented_code.append(f'helper.SetChannelAttribute("Delay", StringValue("{dly}"));')
        if ltype == "p2p":
            indented_code.append(f'helper.SetDeviceAttribute("DataRate", StringValue("{rate}"));')
        indented_code.append(f'helper.EnablePcapAll("link{idx}");')
        indented_code.append(f"linkDevices = helper.Install(linkNodes);")

    indented_code.append(f'Ipv4AddressHelper ipv4;')
    indented_code.append(f'ipv4.SetBase("10.{addr_oct}.0.0", "255.255.255.0");')
    indented_code.append(f'ipv4.Assign(linkDevices);')
    
    for line in indented_code:
        code.append("    " + line)

    code.append("  }\n")
    addr_oct += 1

code.append('  Ipv4GlobalRoutingHelper::PopulateRoutingTables();\n')

if not traffic:
    sinks  = [n for n in nodes if n["role"] == "sink"]
    if not sinks: die("No sink node and no 'traffic_flows' section in YAML.")
    default_sink = sinks[0]["name"]
    traffic = [{"source": n["name"], "sink": default_sink} for n in nodes if n["role"] == "source"]

code.append("  uint16_t sinkPort = 8080;")

unique_sinks = {t['sink'] for t in traffic}
for sink_name in unique_sinks:
    sink_cpp = node_cpp[sink_name]
    code.append("  {")
    code.extend(textwrap.indent(textwrap.dedent(f"""\
        PacketSinkHelper packetSinkHelper("ns3::UdpSocketFactory", InetSocketAddress(Ipv4Address::GetAny(), sinkPort));
        ApplicationContainer sinkApp = packetSinkHelper.Install({sink_cpp});
        sinkApp.Get(0)->TraceConnectWithoutContext("Rx", MakeCallback(&RxPacket));
        sinkApp.Start(Seconds(0.0));
        sinkApp.Stop(Seconds({sim_time}));
    """), "    ").splitlines())
    code.append("  }")

for i, t in enumerate(traffic, 1):
    src_node_name = t['source']
    sink_node_name = t['sink']
    params = t.get("parameters", {})
    rate   = params.get("rate", "1Mbps")
    psize  = params.get("packet_size", 1024)
    start  = params.get("start_time", 1.0)
    stop   = params.get("stop_time", sim_time)
    
    src_cpp = node_cpp[src_node_name]
    sink_cpp = node_cpp[sink_node_name]

    code.append( "  {")
    code.extend(textwrap.indent(textwrap.dedent(f"""\
        Ipv4Address sinkAddress = {sink_cpp}->GetObject<Ipv4>()->GetAddress(1, 0).GetLocal();
        OnOffHelper onOffHelper("ns3::UdpSocketFactory", InetSocketAddress(sinkAddress, sinkPort));
        onOffHelper.SetAttribute("DataRate", StringValue("{rate}"));
        onOffHelper.SetAttribute("PacketSize", UintegerValue({psize}));
        ApplicationContainer sourceApps = onOffHelper.Install({src_cpp});
        sourceApps.Start(Seconds({start}));
        sourceApps.Stop(Seconds({stop}));
    """), "    ").splitlines())
    code.append( "  }")

# ==============================================================================
# FIXED: The Node Roster logic is now robust for all nodes, including routers.
# ==============================================================================
code.append('\n  NS_LOG_UNCOND("===== Node Roster (All IPs per Node) =====");')
for n in nodes:
    cpp, name, role = node_cpp[n["name"]], n["name"], n["role"]
    # This C++ block iterates through all interfaces on a node and all addresses on each interface.
    cpp_code_block = textwrap.dedent(f"""\
      {{
        Ptr<Ipv4> ipv4 = {cpp}->GetObject<Ipv4>();
        NS_LOG_UNCOND("Node " << {cpp}->GetId() << ": {name} ({role})");
        // We start the interface loop at 1 to skip the loopback device (lo, 127.0.0.1)
        for(uint32_t i = 1; i < ipv4->GetNInterfaces(); i++)
        {{
          // An interface can have multiple IP addresses. We log all of them.
          for(uint32_t j = 0; j < ipv4->GetNAddresses(i); j++)
          {{
            Ipv4InterfaceAddress interfaceAddress = ipv4->GetAddress(i, j);
            Ipv4Address ip = interfaceAddress.GetLocal();
            NS_LOG_UNCOND("  - Interface " << i << ", Address " << j << ": " << ip);
          }}
        }}
      }}
    """)
    code.append(textwrap.indent(cpp_code_block, "  "))


code.append(f"\n  Simulator::Stop(Seconds({sim_time}));")
code.append(C_TAIL)

pathlib.Path(out_cc).write_text("\n".join(code))
print(f"[generate_ns3] Wrote C++ simulation file to {out_cc}")