#!/usr/bin/env python3

# Generating ns3 network files 

#Support wifi, p2p, packet tracing


import sys, pathlib, yaml, textwrap

def die(msg): sys.exit(f"[generate_ns3] {msg}")
if len(sys.argv) != 2: die("usage: generate_ns3.py <config.yaml>")

cfg = yaml.safe_load(pathlib.Path(sys.argv[1]).read_text())
sim_name = cfg.get("sim_name", "Network")
sim_time = cfg.get("sim_time", 10)
nodes    = cfg["nodes"]
links    = cfg["links"]
traffic  = cfg.get("traffic")

def cpp_id(s): return "".join(c if c.isalnum() else "_" for c in s)
node_cpp = {n["name"]: cpp_id(n["name"]) for n in nodes}
node_map = {n["name"]: n            for n in nodes}

def infer_type(link):
    if "type" in link: return link["type"]
    a, b = node_map[link["src"]]["network"], node_map[link["dest"]]["network"]
    return "wifi" if "wifi" in (a, b) else a

out_cc   = f"{cpp_id(sim_name)}.cc"

# C++ base/body
C_HEAD = textwrap.dedent(f"""\
    /*  AUTOGENERATED from {pathlib.Path(sys.argv[1]).name} */
    #include "ns3/core-module.h"
    #include "ns3/network-module.h"
    #include "ns3/internet-module.h"
    #include "ns3/point-to-point-module.h"
    #include "ns3/csma-module.h"
    #include "ns3/wifi-module.h"
    #include "ns3/mobility-module.h"
    #include "ns3/applications-module.h"

    using namespace ns3;

    static uint32_t pktTx = 0, pktRx = 0;
    static void TxCb(Ptr<const Packet>)               {{ ++pktTx; }}
    static void RxCb(Ptr<const Packet>, const Address&) {{ ++pktRx; }}

    int main(int argc, char* argv[]) {{
      Time::SetResolution(Time::NS);
      CommandLine cmd; cmd.Parse(argc, argv);
      NS_LOG_UNCOND("===== {sim_name} start =====");
""")

C_TAIL = textwrap.dedent(f"""\
      NS_LOG_UNCOND("[SIM] Tx=" << pktTx << "  Rx=" << pktRx);
      NS_LOG_UNCOND("===== simulation end =====");
      Simulator::Run();
      Simulator::Destroy();
      return 0;
    }}
""")

code = [C_HEAD]

# Nodes for the script 
code.append("  NodeContainer all;")
for n in nodes:
    cpp = node_cpp[n["name"]]
    code.append(f"  Ptr<Node> {cpp} = CreateObject<Node>();")
    code.append(f"  all.Add({cpp});")
code.append("")

# Stacks for download
code.append("  InternetStackHelper internet;")
for cpp in node_cpp.values():
    code.append(f"  internet.Install({cpp});")
code.append('\n  MobilityHelper mob;')
code.append('  mob.SetMobilityModel("ns3::ConstantPositionMobilityModel");')
for cpp in node_cpp.values():
    code.append(f"  mob.Install({cpp});")
code.append("")

# Linking the nodes 
addr_oct, link_meta = 1, []
for idx, ln in enumerate(links, 1):
    ltype = infer_type(ln)
    src_n, dst_n = ln["src"], ln["dest"]
    src_cpp, dst_cpp = node_cpp[src_n], node_cpp[dst_n]
    dev = f"dev{idx}"
    tag = f"link{idx}"
    link_meta.append((ltype, dev, tag))

    code.append(f'  NS_LOG_UNCOND("[INIT] {ltype} {src_n}<->{dst_n}");')
    code.append(f"  NetDeviceContainer {dev};")

    if ltype == "wifi":
        code.extend(textwrap.dedent(f"""\
            {{
              YansWifiChannelHelper chan = YansWifiChannelHelper::Default();
              YansWifiPhyHelper phy; phy.SetChannel(chan.Create());
              WifiHelper wifi; wifi.SetStandard(WIFI_STANDARD_80211g);
              WifiMacHelper mac; Ssid ssid = Ssid("{tag}");
              mac.SetType("ns3::ApWifiMac", "Ssid", SsidValue(ssid));
              NetDeviceContainer apDev  = wifi.Install(phy, mac, {dst_cpp});
              mac.SetType("ns3::StaWifiMac","Ssid", SsidValue(ssid));
              NetDeviceContainer staDev = wifi.Install(phy, mac, {src_cpp});
              {dev}.Add(apDev.Get(0)); {dev}.Add(staDev.Get(0));
              staDev.Get(0)->TraceConnectWithoutContext("PhyTxEnd", MakeCallback(&TxCb));
              YansWifiPhyHelper().EnablePcap("{tag}", {dev}, true);
            }}
        """).splitlines())
    else:
        hlp  = f"hlp{idx}"
        hcls = "PointToPointHelper" if ltype == "p2p" else "CsmaHelper"
        rate = ln.get("data_rate", "100Mbps")
        dly  = ln.get("delay", "2ms")
        code.append(f"  {hcls} {hlp};")
        code.append(f'  {hlp}.SetChannelAttribute("Delay", StringValue("{dly}"));')
        if ltype == "p2p":
            code.append(f'  {hlp}.SetDeviceAttribute("DataRate", StringValue("{rate}"));')
        code.append(f"  {dev} = {hlp}.Install({src_cpp}, {dst_cpp});")
        code.append(f'  {hlp}.EnablePcapAll("{tag}");')

    code.append(f'  Ipv4AddressHelper ip{idx};')
    code.append(f'  ip{idx}.SetBase("10.{addr_oct}.0.0", "255.255.255.0");')
    code.append(f'  ip{idx}.Assign({dev});\n')
    addr_oct += 1

# Setting up the packet traffic if it exists 
if not traffic:
    sinks  = [n for n in nodes if n["role"] == "sink"]
    if not sinks: die("No sink node and no traffic section.")
    default_sink = sinks[0]["name"]
    traffic = [{"src": n["name"], "dest": default_sink}
               for n in nodes if n["role"] == "source"]

code.append('  NS_LOG_UNCOND("[INIT] Installing traffic …");')
code.append("  uint16_t port = 9000;")

# Sinks
for dst in {t["dest"] for t in traffic}:
    cpp = node_cpp[dst]
    code.append('  PacketSinkHelper sh("ns3::UdpSocketFactory",'
                ' InetSocketAddress(Ipv4Address::GetAny(), port));')
    code.append(f"  auto sinkApp = sh.Install({cpp});")
    code.append("  sinkApp.Get(0)->TraceConnectWithoutContext(\"Rx\", MakeCallback(&RxCb));")
    code.append(f"  sinkApp.Start(Seconds(0)); sinkApp.Stop(Seconds({sim_time}));")

# sources
for i, t in enumerate(traffic, 1):
    s_cpp, d_cpp = node_cpp[t["src"]], node_cpp[t["dest"]]
    rate   = t.get("rate", "1Mbps")
    psize  = t.get("pkt_size", 512)
    proto  = "Udp"
    code.extend(textwrap.dedent(f"""\
        {{
          Ipv4Address dst = {d_cpp}->GetObject<Ipv4>()->GetAddress(1,0).GetLocal();
          OnOffHelper on("ns3::{proto}SocketFactory", Address(InetSocketAddress(dst, port)));
          on.SetAttribute("DataRate", DataRateValue(DataRate("{rate}")));
          on.SetAttribute("PacketSize", UintegerValue({psize}));
          auto a{i} = on.Install({s_cpp});
          a{i}.Start(Seconds(1.0)); a{i}.Stop(Seconds({sim_time}));
        }}
    """).splitlines())

code.append('  NS_LOG_UNCOND("[INFO] Node roster:");')
for n in nodes:
    cpp, role = node_cpp[n["name"]], n["role"]
    code.append(f'  NS_LOG_UNCOND(" id=" << {cpp}->GetId() << " name={n["name"]} role={role} ip="'
                f' << {cpp}->GetObject<Ipv4>()->GetAddress(1,0).GetLocal());')

code.append(f"  Simulator::Stop(Seconds({sim_time}));")
code.append(C_TAIL)

pathlib.Path(out_cc).write_text("\n".join(code))
print(f"[generate_ns3] wrote {out_cc}")
